# Generated by Django 4.2.5 on 2023-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mkgif", "0002_animation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="animation",
            name="type",
            field=models.TextField(default="gif", max_length=5),
            preserve_default=False,
        ),
    ]
