# Generated by Django 4.2.5 on 2023-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mkgif", "0003_animation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="animation",
            name="status",
            field=models.CharField(
                choices=[("processing", "Processing"), ("complete", "Complete")],
                default="processing",
                max_length=10,
            ),
        ),
    ]
