# Generated by Django 4.2.5 on 2023-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mkgif", "0006_job_youtubevideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="file_token",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
